use winapi::shared::minwindef::LPVOID;

#[repr(C)]
#[derive(Debug)]
pub struct RiotAudioIVoComponent {
    vtable: LPVOID,
}

#[repr(u32)]
#[derive(Debug)]
pub enum RiotAudioVoComponentEventType {
    VoCommandAttackCharge = 0x0,
    VoCommandAttackHey = 0x1,
    VoCommandDefendAllyChampion = 0x2,
    VoCommandAttackEnemyChampion = 0x3,
    VoCommandDefendAllyTower = 0x4,
    VoCommandDefendAllyInhibitor = 0x5,
    VoCommandDefendAllyNexus = 0x6,
    VoCommandDefendAllyCapturePoint = 0x7,
    VoCommandAttackEnemyTower = 0x8,
    VoCommandAttackNeutralMonster = 0x9,
    VoCommandAttackWorm = 0xA,
    VoCommandAttackDragon = 0xB,
    VoCommandAttackEnemyInhibitor = 0xC,
    VoCommandAttackEnemyNexus = 0xD,
    VoCommandAttackNeutralCapturePoint = 0xE,
    VoCommandDefendSelf = 0xF,
    VoCommandDangerOpenSpace = 0x10,
    VoCommandBack = 0x11,
    VoCommandDangerEnemyChampion = 0x12,
    VoCommandDangerEnemyTower = 0x13,
    VoCommandDangerEnemyCapturePoint = 0x14,
    VoCommandAttentionSelf = 0x15,
    VoCommandNonposOutofmana = 0x16,
    VoCommandNonposHelp = 0x17,
    VoCommandNonposThanks = 0x18,
    VoCommandNonposNicejob = 0x19,
    VoCommandNonposMia = 0x1A,
    VoCommandNonposNevermind = 0x1B,
    VoCommandNonposSorry = 0x1C,
    VoCommandNonposOnmyway = 0x1D,
    VoCommandNonposYes = 0x1E,
    VoCommandNonposNo = 0x1F,
    VoAnnouncementKillChampion = 0x20,
    VoAnnouncementEndSpree = 0x21,
    VoInteractiveRevive = 0x22,
    VoInteractiveIdleInBrush = 0x23,
    VoInteractiveKillEpic = 0x24,
    VoInteractiveAssistAlly = 0x25,
    VoInteractivePlaceWard = 0x26,
    VoInteractiveAssistThanks = 0x27,
    VoInteractiveBluepill = 0x28,
    VoInteractiveSigilAcquired = 0x29,
    VoInteractiveRevealEnemyNashorKill = 0x2A,
    VoInteractiveRevealEnemyDragonKill = 0x2B,
    VoInteractiveRevealEnemyBuffSteal = 0x2C,
    VoInteractiveAcquireGreaterRelic = 0x2D,
    VoInteractiveAcquireHealthRelic = 0x2E,
    VoInteractiveAcquireSpeedBuff = 0x2F,
    VoInteractiveHeal = 0x30,
    VoSummonerPlatform = 0x31,
    VoInteractiveChampionSpecific1 = 0x32,
    VoInteractiveChampionSpecific2 = 0x33,
    VoInteractiveChampionSpecific3 = 0x34,
    VoInteractiveChampionSpecific4 = 0x35,
    VoInteractiveChampionSpecific5 = 0x36,
    VoInteractiveChampionSpecific6 = 0x37,
    VoInteractiveChampionSpecific7 = 0x38,
    VoInteractiveChampionSpecific8 = 0x39,
    VoInteractiveChampionSpecific9 = 0x3A,
    VoInteractiveLevelUp = 0x3B,
    VoInteractiveUltimateReady = 0x3C,
    VoInteractivePurchaseItem = 0x3D,
    VoInteractiveKillMinion = 0x3E,
    VoOrderackAttack = 0x3F,
    VoOrderackUse = 0x40,
    VoInteractiveClearNeutralCamp = 0x41,
    VoShopMenuOpen = 0x42,
    VoShopPurchaseItem = 0x43,
    VoShopClose = 0x44,
    VoShopBrowsing = 0x45,
    VoShopAmbient = 0x46,
    VoShopForgotItems = 0x47,
    VoShopMenuOpenRich = 0x48,
    VoShopMenuOpenMultiTimes = 0x49,
}
