name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    #- name: Set current Time as an environment variable
    #  run: |
    #    echo "::set-env name=NOW_TAG::$(date +'v%d%m%Y.%H%M%S')"
    #    echo "::set-env name=NOW::$(date +'%d-%m-%Y-%H:%M:%S')"
    
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: i686-pc-windows-msvc
        override: true
        profile: minimal 
    
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Upload loader to artifact
      uses: actions/upload-artifact@v1
      with:
        name: sidonia-release-x86
        path: target/i686-pc-windows-msvc/release/sidonia.exe
    
    - name: Upload core to artifact
      uses: actions/upload-artifact@v1
      with:
        name: sidonia-release-x86
        path: target/i686-pc-windows-msvc/release/sidonia_core.dll
