name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: i686-pc-windows-msvc
        override: true
        profile: minimal 
    - name: Build
      run: cargo build --release --verbose
    
    - uses: actions/upload-artifact@v1
      with:
        name: sidonia-release-x86
        path: |
          ..\target\i686-pc-windows-msvc\release
          !..\target\i686-pc-windows-msvc\release\*\*.*
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
